### ISSUE TITLE
Documentation: add tested OS in README and manual.

### ISSUE THREAD

**Issue by JowieXiang** [citysciencelab/open-city-toolkit#146]
**Transerve requirement**: Since Linux OS has many variants and dependencies change with the version, the tutorial should mention the details regarding version and dependencies.

**Comment by LisaReudenbach** [comment]
The manual states quite clearly that the recommended way of installing
the OCT is with Docker, in which case the Linux variant of the container
(the OCT) is fixed and the one of the host is almost irrelevant. I have
decided to establish the use of Docker back then because it allows us to
widely ignore the host system's specifics and to focus more on the
application itself (and also because it helped me in my effort to
transfer the tool from Titusz' computer to mine).

Nowadays Docker is a very well-known industry standard that we can
simply require. So let's not waste time on compiling a list of Linux
flavours and insist that Docker be used for installation. (A large
amount of tutorials on how to install and use Docker can be found on the
Internet.)

**Comment by LisaReudenbach** [comment]
Maybe we should discuss whether we should ensure compatibility with Windows. In theory
it is possible to deploy the OCT with Docker on Windows, but in practice
there will be issues (I have observed this in the call I had with
Latacunga last year; it didn't work out of the box).
