### ISSUE TITLE
Show location boundary

### ISSUE THREAD

**Issue by janbehrens** [citysciencelab/open-city-toolkit#3]
If a basemap location has been added, give a visual indication of the extents of that location.

**Comment by JowieXiang** [comment]
Instead of the whole basemap, I currently use the multipolygon layer, which are the buildings/municipal boundaries, to generate the bounding box. Because some road lines extend very long out of the city, which will cause the bounding box to be unnecessarily large - and it makes no sense at the moment for the user to set the selection to somewhere without any urban infrastructure or human activity.
