### ISSUE TITLE
The layer switcher does not need via point, stricken point, from point and to-point.

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#71]
These should be combined in the 'drawings on the map' layer - no sense to tun them on and off separately.

**Comment by JowieXiang** [comment]
This is a good one ;)

**Comment by janbehrens** [comment]
The "drawings on the map" layer is where the drawings show up. Its contents controlled by the drawing tool and its create/delete functions. Thus, its contents are ephemeral. From points, via points, and to points, on the other hand, are not ephemeral. As a user I want to see where I put the from (via, to) points even after I've cleared the drawings layer. That's why they are not redundant.

**Comment by JowieXiang** [comment]
> The "drawings on the map" layer is where the drawings show up. Its contents are controlled by the drawing tool and its create/delete functions. Thus, its contents are ephemeral. From points, via points, and to points, on the other hand, are not ephemeral. As a user I want to see where I put the from (via, to) points even after I've cleared the drawings layer. That's why they are not redundant.

Ah you're right. Should we do anything about this, or leave it as it is?

**Comment by JowieXiang** [comment]
Added a fix in this commit 09bae33.
Now when the use starts 'Calculate Time Map' module, the via/from/to points and the stricken area layers are automatically switched on in the map.

**Comment by LisaReudenbach** [comment]
ok, thanks @janbehrens - now I understand the difference and the need to keep both. However, there is no option to define 'to points' in the instructions for the 'calculate time map' module, so these should be removed, right?

**Comment by janbehrens** [comment]
In the revised version of the time map module, there are no more "to points", that's right. So we can remove that layer...
