### ISSUE TITLE
Results for time map module does not show up on the map

### ISSUE THREAD

**Issue by ArjamaM** [citysciencelab/open-city-toolkit#83]

**Comment by Ariel505** [comment]
Not sure if this bug is time map result css configuration related.
I tried this timemap function with following input:
1. click multiple start point in the map by reference latacunga safe points and sirens. (see volcano_risk)
![1_volcano_risk](https://user-images.githubusercontent.com/37367728/99253912-d3ecd200-2811-11eb-85d5-a9f588a6a3e5.PNG)

2. draw a restriction area referencing volcano threat layer (see restriction)
![2_restriction](https://user-images.githubusercontent.com/37367728/99253960-e5ce7500-2811-11eb-8f62-6e1834fe56fe.PNG)

3. set reducing speed=0, skip other parameters, perform time map calculation.

4. vector shown in the PDF is fine, value ranges from 0 to 20. 
[time_map_results_2020-11-16_1142.pdf](https://github.com/citysciencelab/open-city-toolkit/files/5546240/time_map_results_2020-11-16_1142.pdf)

5. Image tiles shows transparent on the GUI (see debuger)
![4_Debugger](https://user-images.githubusercontent.com/37367728/99254032-04347080-2812-11eb-89d3-4e332263e48b.PNG)

6. m1 time map raster can display correctly here in the QGIS (see QGIS)
![5_QGIS](https://user-images.githubusercontent.com/37367728/99254111-21693f00-2812-11eb-8adc-2883322c3eee.PNG)

**Comment by Ariel505** [comment]
time_map CSS configuration in GeoServer:

/*@ title Temp map */
* {
  raster-channels: auto;
  raster-opacity:0.5;

  raster-color-map: color-map-entry(#ff3933, 0)
    				color-map-entry(#ff6b33, 0.8)
    				color-map-entry(#ff9333, 1.35)
    				color-map-entry(#ffb533, 2)
    				color-map-entry(#ffdd33, 3)
    				color-map-entry(#f9ff33, 4)
    				color-map-entry(#d1ff33, 5)
    				color-map-entry(#a5ff33, 6)
    				color-map-entry(#7aff33, 7)
    				color-map-entry(#42ff33, 8)
    				color-map-entry(#33ff4f, 9)
    				color-map-entry(#33ff86, 10)
    				color-map-entry(#33ffb5, 12)
    				color-map-entry(#33ffdd, 15)
    				color-map-entry(#33f3ff, 18)
    				color-map-entry(#33c4ff, 20)
    				color-map-entry(#3396ff, 25)
    				color-map-entry(#3368ff, 30)
    				color-map-entry(#3346ff, 35)
    				color-map-entry(#4c33ff, 40)
    				color-map-entry(#8333ff, 45)
    				color-map-entry(#ca33ff, 50)
    				color-map-entry(#fc33ff, 55)
    				color-map-entry(#ff33ca, 60);
}

**Comment by janbehrens** [comment]
Hi,
I tried to reproduce your analysis and here is my result.

![grafik](https://user-images.githubusercontent.com/36447927/99401387-6c558600-28e8-11eb-9090-4bc508b8a948.png)

The lines are very thin, but they are there.

**Comment by Ariel505** [comment]
I changed the result time map from raster into vector point and apply new symbology. It pretty solved this issue.

![Time_map](https://user-images.githubusercontent.com/37367728/99658960-73070900-2a60-11eb-9906-b461ab80e114.PNG)

**Comment by Ariel505** [comment]
changes of script and geoserver layer configuration will send pull request later in this week.

**Comment by janbehrens** [comment]
Thanks, it looks great!
Can you reverse the symbology so the closest places become green and the most distant ones become red?
